name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/premake/premake-core/releases/latest | grep "browser_download_url" | grep "linux" | cut -d '"' -f 4)
          wget $LATEST_URL -O premake.tar.gz
          tar -xvzf premake.tar.gz
          sudo mv premake5 /usr/local/bin/premake5
          premake5 --version

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          	echo "Installing Premake5 via PowerShell..."
		$response = Invoke-RestMethod -Uri "https://api.github.com/repos/premake/premake-core/releases/latest"
          	$url = $response.assets | Where-Object { $_.name -match "premake5-windows-x64.zip" } | Select-Object -ExpandProperty browser_download_url
          
          	if ($url) 
          	{
              Write-Host "Found Premake5 download URL: $url"
              $output = "premake5.zip"
              Invoke-WebRequest -Uri $url -OutFile $output
              Expand-Archive -Path $output -DestinationPath .
              Move-Item -Path ".\premake5.exe" -Destination "C:\Program Files\Premake5\premake5.exe"
              [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Premake5", [System.EnvironmentVariableTarget]::Machine)
              premake5 --version
          } 
          else 
          {
              Write-Error "Premake5 Windows version not found."
              exit 1
          }
          
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install premake
          premake5 --version

      - name: Configure project with Premake
        run: premake5 ninja

      - name: Build project
        run: ninja -C build
