name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Install tools cross-platform
      - name: Install tools
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .\scripts\install_tools.ps1 -Verbose
      - name: Install tools (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/install_tools.sh --verbose

      # 2. Ensure local bin in PATH
      - name: Add .local/bin to PATH
        run: echo "${{ env.HOME }}/.local/bin" >> $GITHUB_PATH

      # 3. Fetch dependencies
      - name: Fetch dependencies
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\fetch_dependencies.ps1
      - name: Fetch dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/fetch_dependencies.sh

      # 4. Generate build files
      - name: Generate build files
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            premake5.exe ninja
          else
            premake5 ninja
          fi

      # 5. Build
      - name: Build
        run: ninja -C build