name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ══════════════════════════════ Linux/macOS ══════════════════════════════
      - name: Make shell scripts executable
        if: runner.os != 'Windows'
        run: |
          chmod +x ./scripts/install_tools.sh
          chmod +x ./scripts/fetch_dependencies.sh

      - name: Install tools
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/install_tools.sh

      # ══════════════════════════════ Windows ══════════════════════════════
      - name: Set up MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install tools
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./scripts/install_tools.ps1

      - name: Add premake5 path to GitHub Actions PATH
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $PremakePath = "$env:USERPROFILE\.local\bin"
          echo "$PremakePath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # ══════════════════════════════ Build (Common) ══════════════════════════════
      - name: Generate build files with premake-ninja
        run: premake5 ninja

      - name: Build project with Ninja
        run: ninja -C build
