name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git and compiler (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install git g++ -y
          g++ --version
          git --version

      - name: Install Git and compiler (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install git llvm
          export CC=/opt/homebrew/opt/llvm/bin/clang
          export CXX=/opt/homebrew/opt/llvm/bin/clang++
          clang++ --version
          git --version

      - name: Install Git and compiler (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install git --yes
          git --version
          # MSVC is preinstalled in Windows runners
          cl

      - name: Setup tools
        run: |
          cd scripts
          if [ "$RUNNER_OS" = "Windows" ]; then
            pwsh ./install_tools.ps1
          else
            bash ./install_tools.sh
          fi

      - name: Fetch dependencies
        run: |
          cd scripts
          if [ "$RUNNER_OS" = "Windows" ]; then
            pwsh ./fetch_dependencies.ps1
          else
            bash ./fetch_dependencies.sh
          fi

      - name: Configure project
        run: premake5 ninja

      - name: Build project
        run: ninja -C build
