name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ══ Linux/macOS ════════════════════════════════════════════
      - name: Make shell scripts executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./scripts/install_tools.sh
          chmod +x ./scripts/fetch_dependencies.sh

      - name: Install tools (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/install_tools.sh

      - name: Fetch dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/fetch_dependencies.sh

      # ══ Windows ═══════════════════════════════════════════════
      - name: Set up MSVC (Developer Command Prompt)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install tools (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\install_tools.ps1

      - name: Add .local/bin to PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: echo "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Fetch dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: .\scripts\fetch_dependencies.ps1

      # ══ Common Build Steps ═════════════════════════════════════
      - name: Generate build files
        run: premake5 ninja

      - name: Build
        run: ninja -C build