name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Installing Premake5 via PowerShell..."
          LATEST_URL=$(curl -s https://api.github.com/repos/premake/premake-core/releases/latest | grep "browser_download_url" | grep "linux" | cut -d '"' -f 4)
          wget $LATEST_URL -O premake.tar.gz
          tar -xvzf premake.tar.gz
          sudo mv premake5 /usr/local/bin/premake5
          premake5 --version

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Installing Premake5 via PowerShell..."
          $url = "https://github.com/premake/premake-core/releases/latest/download/premake5-windows-x64.zip"
          $output = "premake5.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath .
          Move-Item -Path ".\premake5.exe" -Destination "C:\Program Files\Premake5\premake5.exe"
          $env:Path += ";C:\Program Files\Premake5"
          premake5 --version
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Premake5", [System.EnvironmentVariableTarget]::Machine)
          premake5 --version

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "Installing Premake5 via Brew..."
          brew update
          brew install premake
          premake5 --version

      - name: Configure project with Premake
        run: premake5 ninja

      - name: Build project
        run: ninja -C build
